[package]
name = "ic_siwe"
version = "0.0.6"
edition = "2021"
authors = ["Kristofer Lund <kristofer@kristoferlund.se>"]
description = "Integrate Ethereum wallet-based authentication (SIWE) with applications on the Internet Computer (ICP) platform."
license = "MIT"
homepage = "https://github.com/kristoferlund/ic-siwe"
repository = "https://github.com/kristoferlund/ic-siwe"
keywords = ["ethereum", "wallet", "internet-computer", "authentication", "siwe"]
categories = ["authentication", "cryptography::cryptocurrencies"]

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.66"
serde_bytes = "0.11"
serde_cbor = "0.11"
candid = "0.10"
hex = "0.4.3"
ic-cdk = "0.13"
ic-certified-map = "0.4.0"
url = "2.4.1"
time = { version = "0.3.30", features = ["formatting"] }
rand_chacha = { version = "0.3.1", optional = true }
getrandom = { version = "0.2.10", features = ["custom"] }
k256 = "0.13.2"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = "0.9.1"
simple_asn1 = "0.6.2"

[dev-dependencies]
ethers = "2.0.10"
tokio = { version = "1.13.0", features = ["full"] }
rand = "0.8.4"
hex-literal = "0.2.1"

[features]
nonce = ["rand_chacha"]
